### ISSUE TITLE
"Import from Github" es una función premium

### ISSUE THREAD

**Issue by jesi-rgb** [fcharte/TFGLatexTemplate#1]
He probado a realizar todos los pasos tal y como describes en el README pero existe un problema: Overleaf solo deja interactuar con GitHub si se trata de una cuenta premium. He tratado de iniciar sesión con mi cuenta de estudiante de la UJA (tal y como lo haría cualquier estudiante) e incluso la de la UGR pero dice que "esta institución no ofrece planes de estudiante todavía".

Creo que lo más fácil sería simplmemente clonar el repositorio localmente y darle a la opción de `Nuevo proyecto > Subir proyecto`.

**Comment by fcharte** [comment]
En principio la plantilla la he preparado para los estudiantes de TFG que tengo este curso y ellos la han podido usar sin problemas clonándola a sus Github. Yo no tengo cuenta premium y he podido importar desde ahí a Overleaf, pero en cualquier caso siempre existe la alternativa que indicas de subir los archivos como un nuevo proyecto tras hacer una clonación en local.
